input_path: "data/data_jmlr_vol13-21.json"
output_path: "results/test.json"
use_title: False
preprocessing:
  stemming: False
  lemmatization: True
  lib: "nltk"
  min_word_len: 2
  max_word_len: 15
  custom_stopwords: []
dimensionality_reduction: None
clustering:
  model: "kmeans"
  n_clusters: 15
